services:
  web:
    build: .
    ports:
      - "5000:80"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      - ./.env
    environment:
      REDIS_URL: rediss://red-cu4gdsd6l47c73b38r30:E8G4LP8K90wMhBwPBydlJGTVZ0x5AC1M@oregon-redis.render.com:6379
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myapp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  email:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    working_dir: /app
    command: flask run --host=0.0.0.0
volumes:
  postgres_data: