services:
  web:
    build: .
    ports:
      - "5000:80"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - ./.env
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myapp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  email:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    working_dir: /app
    command: flask run --host=0.0.0.0
volumes:
  postgres_data: