"""empty message

Revision ID: 49236f7dd185
Revises: 9da039c131d9
Create Date: 2025-01-15 13:17:52.708606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49236f7dd185'
down_revision = '9da039c131d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
